---
name: CI
permissions:
  contents: read

on:
  push:


# Note: we prefer to pin ubuntu versions explicitly rather than use
# ubuntu:latest, as that changes underneath us.
jobs:
  check:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v7
      - uses: "opensafely-core/setup-action@v1"
        with:
          install-uv: true
          install-just: true
          cache: uv
      - name: Check formatting, linting and import sorting
        run: just check

  test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]

    steps:
      - uses: actions/checkout@v7
      - uses: "opensafely-core/setup-action@v1"
        with:
          install-uv: true
          install-just: true
          cache: uv
          python-version: ${{ matrix.python-version }}
      - name: Run tests
        #env:  # Add environment variables required for tests
        run: |
          just test
